name: Deploy Question Engine to AWS Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Get CloudFormation exports
        id: get_exports
        run: |
          echo "Fetching CloudFormation exports..."
          SHARED_API_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='SharedApiId'].Value" \
            --output text)
          SHARED_API_AUTHORIZER_ID=$(aws cloudformation list-exports \
            --query "Exports[?Name=='SharedApiAuthorizerId'].Value" \
            --output text)
          PRIVATE_SG=$(aws cloudformation list-exports \
            --query "Exports[?Name=='NetworkStack-PrivateSG'].Value" \
            --output text)
          PRIVATE_SUBNETS=$(aws cloudformation list-exports \
            --query "Exports[?Name=='NetworkStack-PrivateSubnetIds'].Value" \
            --output text)
          
          if [ -z "$SHARED_API_ID" ]; then
            echo "::error::SharedApiId export not found"
            exit 1
          fi
          if [ -z "$SHARED_API_AUTHORIZER_ID" ]; then
            echo "::error::SharedApiAuthorizerId export not found"
            exit 1
          fi
          
          echo "shared_api_id=$SHARED_API_ID" >> $GITHUB_OUTPUT
          echo "shared_api_authorizer_id=$SHARED_API_AUTHORIZER_ID" >> $GITHUB_OUTPUT
          echo "private_sg=$PRIVATE_SG" >> $GITHUB_OUTPUT
          echo "private_subnets=$PRIVATE_SUBNETS" >> $GITHUB_OUTPUT

      - name: Build SAM
        run: sam build --template-file infra/QuestionEngine-template.yaml

      - name: Deploy SAM
        run: |
          sam deploy \
            --parameter-overrides \
              "Environment=dev" \
              "SharedApiId=${{ steps.get_exports.outputs.shared_api_id }}" \
              "SharedApiAuthorizerId=${{ steps.get_exports.outputs.shared_api_authorizer_id }}" \
              "PrivateSG=${{ steps.get_exports.outputs.private_sg }}" \
              "PrivateSubnetIds=${{ steps.get_exports.outputs.private_subnets }}" \
            --config-env default
